server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: Customer-Service
          uri: http://localhost:8084
          predicates:
            - Path=/customer/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles:
                  - admin
                  - user

        - id: Product-Service
          uri: http://localhost:8085
          predicates:
            - Path=/product/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles:
                  - admin

        - id: Dashboard-Service
          uri: http://localhost:8082
          predicates:
            - Path=/dashboard/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles:
                  - admin
                  - user

#        - id: booking-service
#          uri: http://localhost:8085
#          predicates:
#            - Path=/bookings/**
#          filters:
#            - name: JwtAuthFilter
#              args:
#                allowedRoles:
#                  - user
#                  - admin

#  # Cors Configuration
#  web:
#    cors:
#      allowed-origins: "http://localhost:4200"
#      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
#      allowed-headers: "Authorization, Content-Type, Accept, X-Requested-With, Cache-Control"
#      allow-credentials: true
#      max-age: 3600
