spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diary_service_wipro
    username: root
    password: SatyamN.26.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081



